package ru.malik.testproject.entity.DAO;
// Generated 14.09.2013 1:49:49 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MenBirthday generated by hbm2java
 */
public class MenBirthday  implements java.io.Serializable {


     private int id;
     private String lastname;
     private Date birthday;

    public MenBirthday() {
    }

	
    public MenBirthday(int id, String lastname) {
        this.id = id;
        this.lastname = lastname;
    }
    public MenBirthday(int id, String lastname, Date birthday) {
       this.id = id;
       this.lastname = lastname;
       this.birthday = birthday;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }




}


