package ru.malik.testproject.entity.DAO;
// Generated 14.09.2013 1:49:49 by Hibernate Tools 3.2.1.GA



/**
 * SecondName generated by hbm2java
 */
public class SecondName  implements java.io.Serializable {


     private int if_;
     private String lastname;

    public SecondName() {
    }

    public SecondName(int if_, String lastname) {
       this.if_ = if_;
       this.lastname = lastname;
    }
   
    public int getIf_() {
        return this.if_;
    }
    
    public void setIf_(int if_) {
        this.if_ = if_;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }




}


